function generateResume() {

  const name = document.getElementById("name").value;
  const email = document.getElementById("email").value;
  const education = document.getElementById("education").value;
  const skills = document.getElementById("skills").value;
  const experience = document.getElementById("experience").value;

  const resume = `
========================
        RESUME
========================

Name: ${name}
Email: ${email}

Professional Summary:
A motivated individual seeking opportunities to grow and contribute effectively.

Education:
${education}

Skills:
${skills}

Experience / Projects:
${experience || "Not provided"}

========================
Generated by ResumeAI
========================
`;

  document.getElementById("output").innerText = resume;
}

/* Download */
function downloadResume() {
  const text = document.getElementById("output").innerText;

  const blob = new Blob([text], { type: "text/plain" });
  const link = document.createElement("a");

  link.href = URL.createObjectURL(blob);
  link.download = "resume.txt";
  link.click();
}
